/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountingPeriodsRouteImport } from './routes/accounting-periods'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ManagerExpensesRouteImport } from './routes/manager-expenses'
import { Route as ManagerInvestmentRouteImport } from './routes/manager-investment'
import { Route as ManagerStockRouteImport } from './routes/manager-stock'
import { Route as ManagersRouteImport } from './routes/managers'
import { Route as PosOverviewRouteImport } from './routes/pos-overview'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RestocksRouteImport } from './routes/restocks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StockFlowsRouteImport } from './routes/stock-flows'
import { Route as WeeklyReportRouteImport } from './routes/weekly-report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingPeriodsRoute = AccountingPeriodsRouteImport.update({
  id: '/accounting-periods',
  path: '/accounting-periods',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerExpensesRoute = ManagerExpensesRouteImport.update({
  id: '/manager-expenses',
  path: '/manager-expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerInvestmentRoute = ManagerInvestmentRouteImport.update({
  id: '/manager-investment',
  path: '/manager-investment',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerStockRoute = ManagerStockRouteImport.update({
  id: '/manager-stock',
  path: '/manager-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagersRoute = ManagersRouteImport.update({
  id: '/managers',
  path: '/managers',
  getParentRoute: () => rootRouteImport,
} as any)
const PosOverviewRoute = PosOverviewRouteImport.update({
  id: '/pos-overview',
  path: '/pos-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RestocksRoute = RestocksRouteImport.update({
  id: '/restocks',
  path: '/restocks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StockFlowsRoute = StockFlowsRouteImport.update({
  id: '/stock-flows',
  path: '/stock-flows',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeklyReportRoute = WeeklyReportRouteImport.update({
  id: '/weekly-report',
  path: '/weekly-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounting-periods': typeof AccountingPeriodsRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/manager-expenses': typeof ManagerExpensesRoute
  '/manager-investment': typeof ManagerInvestmentRoute
  '/manager-stock': typeof ManagerStockRoute
  '/managers': typeof ManagersRoute
  '/pos-overview': typeof PosOverviewRoute
  '/reports': typeof ReportsRoute
  '/restocks': typeof RestocksRoute
  '/settings': typeof SettingsRoute
  '/stock-flows': typeof StockFlowsRoute
  '/weekly-report': typeof WeeklyReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounting-periods': typeof AccountingPeriodsRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/manager-expenses': typeof ManagerExpensesRoute
  '/manager-investment': typeof ManagerInvestmentRoute
  '/manager-stock': typeof ManagerStockRoute
  '/managers': typeof ManagersRoute
  '/pos-overview': typeof PosOverviewRoute
  '/reports': typeof ReportsRoute
  '/restocks': typeof RestocksRoute
  '/settings': typeof SettingsRoute
  '/stock-flows': typeof StockFlowsRoute
  '/weekly-report': typeof WeeklyReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounting-periods': typeof AccountingPeriodsRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/expenses': typeof ExpensesRoute
  '/inventory': typeof InventoryRoute
  '/investments': typeof InvestmentsRoute
  '/login': typeof LoginRoute
  '/manager-expenses': typeof ManagerExpensesRoute
  '/manager-investment': typeof ManagerInvestmentRoute
  '/manager-stock': typeof ManagerStockRoute
  '/managers': typeof ManagersRoute
  '/pos-overview': typeof PosOverviewRoute
  '/reports': typeof ReportsRoute
  '/restocks': typeof RestocksRoute
  '/settings': typeof SettingsRoute
  '/stock-flows': typeof StockFlowsRoute
  '/weekly-report': typeof WeeklyReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting-periods'
    | '/activity'
    | '/analytics'
    | '/expenses'
    | '/inventory'
    | '/investments'
    | '/login'
    | '/manager-expenses'
    | '/manager-investment'
    | '/manager-stock'
    | '/managers'
    | '/pos-overview'
    | '/reports'
    | '/restocks'
    | '/settings'
    | '/stock-flows'
    | '/weekly-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting-periods'
    | '/activity'
    | '/analytics'
    | '/expenses'
    | '/inventory'
    | '/investments'
    | '/login'
    | '/manager-expenses'
    | '/manager-investment'
    | '/manager-stock'
    | '/managers'
    | '/pos-overview'
    | '/reports'
    | '/restocks'
    | '/settings'
    | '/stock-flows'
    | '/weekly-report'
  id:
    | '__root__'
    | '/'
    | '/accounting-periods'
    | '/activity'
    | '/analytics'
    | '/expenses'
    | '/inventory'
    | '/investments'
    | '/login'
    | '/manager-expenses'
    | '/manager-investment'
    | '/manager-stock'
    | '/managers'
    | '/pos-overview'
    | '/reports'
    | '/restocks'
    | '/settings'
    | '/stock-flows'
    | '/weekly-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountingPeriodsRoute: typeof AccountingPeriodsRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ExpensesRoute: typeof ExpensesRoute
  InventoryRoute: typeof InventoryRoute
  InvestmentsRoute: typeof InvestmentsRoute
  LoginRoute: typeof LoginRoute
  ManagerExpensesRoute: typeof ManagerExpensesRoute
  ManagerInvestmentRoute: typeof ManagerInvestmentRoute
  ManagerStockRoute: typeof ManagerStockRoute
  ManagersRoute: typeof ManagersRoute
  PosOverviewRoute: typeof PosOverviewRoute
  ReportsRoute: typeof ReportsRoute
  RestocksRoute: typeof RestocksRoute
  SettingsRoute: typeof SettingsRoute
  StockFlowsRoute: typeof StockFlowsRoute
  WeeklyReportRoute: typeof WeeklyReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting-periods': {
      id: '/accounting-periods'
      path: '/accounting-periods'
      fullPath: '/accounting-periods'
      preLoaderRoute: typeof AccountingPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-expenses': {
      id: '/manager-expenses'
      path: '/manager-expenses'
      fullPath: '/manager-expenses'
      preLoaderRoute: typeof ManagerExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-investment': {
      id: '/manager-investment'
      path: '/manager-investment'
      fullPath: '/manager-investment'
      preLoaderRoute: typeof ManagerInvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-stock': {
      id: '/manager-stock'
      path: '/manager-stock'
      fullPath: '/manager-stock'
      preLoaderRoute: typeof ManagerStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managers': {
      id: '/managers'
      path: '/managers'
      fullPath: '/managers'
      preLoaderRoute: typeof ManagersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos-overview': {
      id: '/pos-overview'
      path: '/pos-overview'
      fullPath: '/pos-overview'
      preLoaderRoute: typeof PosOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restocks': {
      id: '/restocks'
      path: '/restocks'
      fullPath: '/restocks'
      preLoaderRoute: typeof RestocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-flows': {
      id: '/stock-flows'
      path: '/stock-flows'
      fullPath: '/stock-flows'
      preLoaderRoute: typeof StockFlowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weekly-report': {
      id: '/weekly-report'
      path: '/weekly-report'
      fullPath: '/weekly-report'
      preLoaderRoute: typeof WeeklyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountingPeriodsRoute: AccountingPeriodsRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  ExpensesRoute: ExpensesRoute,
  InventoryRoute: InventoryRoute,
  InvestmentsRoute: InvestmentsRoute,
  LoginRoute: LoginRoute,
  ManagerExpensesRoute: ManagerExpensesRoute,
  ManagerInvestmentRoute: ManagerInvestmentRoute,
  ManagerStockRoute: ManagerStockRoute,
  ManagersRoute: ManagersRoute,
  PosOverviewRoute: PosOverviewRoute,
  ReportsRoute: ReportsRoute,
  RestocksRoute: RestocksRoute,
  SettingsRoute: SettingsRoute,
  StockFlowsRoute: StockFlowsRoute,
  WeeklyReportRoute: WeeklyReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
